sudo: true
language: cpp
compiler: gcc
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  - ./download_other_githubs.sh
  - ./build_other_githubs.sh
  # Build console test
  - qmake BrainweaverConsoleTest.pro
  - make debug
  # Build and run desktop test
  - qmake BrainweaverDesktopTest.pro
  - make debug
  # Run tests
  - ./BrainweaverConsoleTest
  - ./BrainweaverDesktopTest
  # Get code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov
  # Build 'true' executables
  - qmake BrainweaverDeveloper.pro
  - make debug
  - qmake BrainweaverAssessor.pro
  - make debug
  - qmake BrainweaverStudent.pro
  - make debug
  # Call OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)












